const storageKey="edu-admin-local-prototype-v1";
const navItems=[{id:"dashboard",label:"运营总览",icon:"▦"},{id:"students",label:"学员",icon:"人"},{id:"orders",label:"订单课时",icon:"￥"},{id:"classes",label:"班级",icon:"班"},{id:"schedule",label:"课表",icon:"日"},{id:"consume",label:"消课",icon:"扣"},{id:"templates",label:"模板字段库",icon:"表"}];
const viewMeta={dashboard:["运营总览","今日校区"],students:["学员管理","学员档案"],orders:["订单课时","报名与余额"],classes:["班级管理","分班与容量"],schedule:["排课管理","本周课表"],consume:["消课管理","课时流水"],templates:["导入导出","Excel 模板字段库"]};
let appState=loadState(),currentView="dashboard",searchTerm="";
const appContent=document.querySelector("#appContent"),viewTitle=document.querySelector("#viewTitle"),viewEyebrow=document.querySelector("#viewEyebrow"),navList=document.querySelector("#navList"),globalSearch=document.querySelector("#globalSearch"),studentDialog=document.querySelector("#studentDialog"),studentForm=document.querySelector("#studentForm");
function loadState(){const saved=localStorage.getItem(storageKey);if(!saved)return structuredClone(window.seedData);try{return{...structuredClone(window.seedData),...JSON.parse(saved)}}catch{return structuredClone(window.seedData)}}
function saveState(){localStorage.setItem(storageKey,JSON.stringify(appState))}
function escapeHtml(value){return String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function money(value){return Number(value).toLocaleString("zh-CN",{style:"currency",currency:"CNY",maximumFractionDigits:0})}
function tag(label,tone=""){return`<span class="tag ${tone}">${escapeHtml(label)}</span>`}
function statusTone(value){if(["已报名","开课中","已上课","消课"].includes(value))return"green";if(["意向","招生中","待上课"].includes(value))return"amber";if(["欠费","课时不足"].includes(value))return"red";return""}
function matchesRow(row){if(!searchTerm)return true;return Object.values(row).join(" ").toLowerCase().includes(searchTerm.toLowerCase())}
function renderNav(){const counts={dashboard:"",students:appState.students.length,orders:appState.orders.length,classes:appState.classes.length,schedule:appState.lessons.length,consume:appState.ledger.length,templates:appState.templates.length};navList.innerHTML=navItems.map(item=>`<button class="nav-button" type="button" data-view="${item.id}" aria-current="${currentView===item.id?"page":"false"}"><span aria-hidden="true">${item.icon}</span><span>${item.label}</span><span class="nav-count">${counts[item.id]??""}</span></button>`).join("")}
function setView(view){currentView=view;const[eyebrow,title]=viewMeta[view];viewEyebrow.textContent=eyebrow;viewTitle.textContent=title;renderNav();renderView()}
function table(headers,rows){return`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${escapeHtml(h)}</th>`).join("")}</tr></thead><tbody>${rows.join("")||`<tr><td colspan="${headers.length}">没有匹配数据</td></tr>`}</tbody></table></div>`}
function renderDashboard(){const debtTotal=appState.orders.reduce((s,o)=>s+Number(o.debt||0),0),lowBalance=appState.students.filter(s=>Number(s.balance)>0&&Number(s.balance)<=3).length,pendingLessons=appState.lessons.filter(l=>l.status==="待上课").length,activeClasses=appState.classes.filter(c=>c.status==="开课中").length;const lessonRows=appState.lessons.filter(l=>l.status==="待上课").slice(0,5).map(l=>`<tr><td>${l.date}</td><td>${l.time}</td><td>${escapeHtml(l.target)}</td><td>${escapeHtml(l.teacher)}</td><td>${escapeHtml(l.room)}</td></tr>`);const reminders=[...appState.students.filter(s=>s.debt>0).map(s=>({title:`${s.name} 有欠费`,detail:`${money(s.debt)}，跟进人：${s.owner}`,tone:"red"})),...appState.students.filter(s=>s.balance>0&&s.balance<=3).map(s=>({title:`${s.name} 课时不足`,detail:`剩余 ${s.balance} 课时，建议提醒续费`,tone:"amber"})),{title:"导入前校验",detail:"手机号、日期、课时、金额、字典值必须先检查",tone:""}];appContent.innerHTML=`<div class="summary-grid"><div class="metric"><span>学员总数</span><strong>${appState.students.length}</strong></div><div class="metric"><span>待上课节</span><strong>${pendingLessons}</strong></div><div class="metric"><span>开课班级</span><strong>${activeClasses}</strong></div><div class="metric"><span>待收欠费</span><strong>${money(debtTotal)}</strong></div></div><div class="layout-two"><section class="section"><div class="section-head"><h3>待处理课表</h3><button class="small-button" data-go="schedule" type="button">查看课表</button></div><div class="section-body">${table(["日期","时间","班级/1对1","教师","教室"],lessonRows)}</div></section><section class="section"><div class="section-head"><h3>运营提醒</h3><span>${tag(`${lowBalance} 个课时不足`,lowBalance?"amber":"green")}</span></div><div class="section-body stack-list">${reminders.map(i=>`<div class="stack-item"><strong>${tag(i.title,i.tone)}</strong><span class="muted">${escapeHtml(i.detail)}</span></div>`).join("")}</div></section></div>`}
function renderStudents(){const rows=appState.students.filter(matchesRow).map(s=>`<tr><td><strong>${escapeHtml(s.name)}</strong><br><span class="muted">${s.id}</span></td><td>${s.phone}<br><span class="muted">${s.relation}</span></td><td>${s.grade}</td><td>${escapeHtml(s.school)}</td><td>${escapeHtml(s.channel)}</td><td>${escapeHtml(s.course)}</td><td>${escapeHtml(s.className)}</td><td>${tag(s.status,statusTone(s.status))}</td><td>${s.balance}</td><td>${s.debt?tag(money(s.debt),"red"):tag("无欠费","green")}</td></tr>`);appContent.innerHTML=`<section class="section"><div class="section-head"><h3>学员列表</h3><div class="action-row"><button class="small-button" type="button" id="resetDemo">恢复演示数据</button><button class="primary-action" type="button" id="newStudentInline">新增学员</button></div></div><div class="section-body">${table(["学员","手机号","年级","学校","渠道","意向/报读课程","班级","状态","剩余课时","欠费"],rows)}</div></section>`}
function renderOrders(){const rows=appState.orders.filter(matchesRow).map(o=>{const balance=Number(o.bought)+Number(o.gift)-Number(o.used);return`<tr><td><strong>${o.id}</strong><br><span class="muted">${escapeHtml(o.owner)}</span></td><td>${escapeHtml(o.student)}</td><td>${escapeHtml(o.course)}</td><td>${escapeHtml(o.className)}</td><td>${o.bought} + ${o.gift}</td><td>${o.used}</td><td>${tag(balance,balance<=3?"amber":"green")}</td><td>${money(o.paid)}</td><td>${o.debt?tag(money(o.debt),"red"):tag("无","green")}</td><td>${o.expireAt}</td></tr>`});appContent.innerHTML=`<section class="section"><div class="section-head"><h3>报名订单与课时账户</h3><span class="muted">余额 = 购买 + 赠送 - 已上</span></div><div class="section-body">${table(["订单号","学员","课程","班级","购买+赠送","已上","余额","实收","欠费","有效期"],rows)}</div></section>`}
function renderClasses(){const rows=appState.classes.filter(matchesRow).map(c=>`<tr><td><strong>${escapeHtml(c.name)}</strong><br><span class="muted">${c.stage}</span></td><td>${escapeHtml(c.course)}</td><td>${escapeHtml(c.teacher)}</td><td>${escapeHtml(c.assistant)}</td><td>${escapeHtml(c.room)}</td><td>${c.students}/${c.capacity}</td><td>${c.deduct}</td><td>${c.teacherHours}</td><td>${tag(c.status,statusTone(c.status))}</td></tr>`);appContent.innerHTML=`<section class="section"><div class="section-head"><h3>班级与容量</h3><span class="muted">支持普通课程和组合课程</span></div><div class="section-body">${table(["班级","关联课程","教师","助教","教室","人数","学生扣课","教师课时","状态"],rows)}</div></section>`}
function renderSchedule(){const days=["周一","周二","周三","周四","周五"];appContent.innerHTML=`<section class="section"><div class="section-head"><h3>本周课表</h3><span class="muted">班级课与 1 对 1 共用冲突视图</span></div><div class="section-body"><div class="board">${days.map(day=>{const lessons=appState.lessons.filter(l=>l.day===day&&matchesRow(l));return`<div class="day-column"><div class="day-head">${day}</div>${lessons.map(l=>`<article class="lesson-card ${l.status==="已上课"?"done":""}"><strong>${l.time} ${tag(l.status,statusTone(l.status))}</strong><span>${escapeHtml(l.target)}</span><span class="muted">${l.subject} / ${escapeHtml(l.teacher)}</span><span class="muted">${escapeHtml(l.room)}</span><button class="small-button" type="button" data-finish-lesson="${l.id}">确认上课</button></article>`).join("")||`<div class="lesson-card"><span class="muted">暂无课程</span></div>`}</div>`}).join("")}</div></div></section>`}
function renderConsume(){const rows=appState.ledger.filter(matchesRow).map(i=>`<tr><td>${i.time}</td><td>${escapeHtml(i.student)}</td><td>${escapeHtml(i.lesson)}</td><td>${tag(i.type,statusTone(i.type))}</td><td>${i.change}</td><td>${i.before}</td><td>${i.after}</td><td>${escapeHtml(i.operator)}</td></tr>`);appContent.innerHTML=`<section class="section"><div class="section-head"><h3>课时流水</h3><span class="muted">每次消课必须可追溯</span></div><div class="section-body">${table(["时间","学员","关联课节","类型","变动","变动前","变动后","操作人"],rows)}</div></section>`}
function renderTemplates(){appContent.innerHTML=`<section class="section"><div class="section-head"><h3>Excel 模板字段库</h3><span class="muted">星号字段为必填项</span></div><div class="section-body"><div class="template-grid">${appState.templates.filter(matchesRow).map(t=>`<article class="template-card"><div><strong>${escapeHtml(t.name)}</strong><p class="muted">${escapeHtml(t.file)}</p></div><div class="field-list">${t.fields.map(f=>`<span class="field-pill ${f.startsWith("*")?"required":""}">${escapeHtml(f)}</span>`).join("")}</div><div class="stack-list">${t.rules.map(r=>`<span class="muted">· ${escapeHtml(r)}</span>`).join("")}</div></article>`).join("")}</div></div></section>`}
function renderView(){({dashboard:renderDashboard,students:renderStudents,orders:renderOrders,classes:renderClasses,schedule:renderSchedule,consume:renderConsume,templates:renderTemplates}[currentView])()}
function addStudent(formData){const nextNumber=appState.students.length+1;appState.students.unshift({id:`S${String(nextNumber).padStart(3,"0")}`,name:formData.get("name").trim(),phone:formData.get("phone").trim(),relation:"母亲",grade:formData.get("grade").trim(),school:"",channel:formData.get("channel").trim(),owner:formData.get("owner").trim(),course:formData.get("course").trim(),className:"待分班",status:"意向",balance:0,debt:0});saveState();setView("students")}
function finishLesson(lessonId){const lesson=appState.lessons.find(i=>i.id===lessonId);if(!lesson||lesson.status==="已上课")return;lesson.status="已上课";const student=appState.students.find(s=>s.className===lesson.target&&s.balance>0);if(student){const before=Number(student.balance);student.balance=Math.max(0,before-1);appState.ledger.unshift({id:`C${Date.now()}`,student:student.name,lesson:`${lesson.target} ${lesson.date}`,type:"消课",change:-1,before,after:student.balance,operator:lesson.teacher,time:new Date().toLocaleString("zh-CN",{hour12:false})})}saveState();renderView();renderNav()}
document.addEventListener("click",event=>{const navButton=event.target.closest("[data-view]");if(navButton)setView(navButton.dataset.view);const goButton=event.target.closest("[data-go]");if(goButton)setView(goButton.dataset.go);const finishButton=event.target.closest("[data-finish-lesson]");if(finishButton)finishLesson(finishButton.dataset.finishLesson);if(event.target.id==="newStudentInline"||event.target.id==="newStudentBtn")studentDialog.showModal();if(event.target.id==="resetDemo"){localStorage.removeItem(storageKey);appState=structuredClone(window.seedData);renderNav();renderView()}});
globalSearch.addEventListener("input",event=>{searchTerm=event.target.value.trim();renderView()});
studentForm.addEventListener("submit",event=>{if(event.submitter?.value==="cancel")return;event.preventDefault();if(!studentForm.reportValidity())return;addStudent(new FormData(studentForm));studentForm.reset();studentDialog.close()});
renderNav();setView("dashboard");
